services:
  web-server:
    build:
      dockerfile: ./docker/web-server-prod/Dockerfile
      context: ./
    networks:
      - web-server-network
    restart: always

networks:
  web-server-network:
    external: true
