services:
  web-server:
    build:
      dockerfile: ./docker/web-server-dev/Dockerfile
      context: ./
    ports:
      - "8000:8000"
    volumes:
      - /srv/app/node_modules
      - ./:/srv/app
    tty: true
